# Generated by Django 2.2.11 on 2020-03-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
