# Generated by Django 2.2.11 on 2020-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200319_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='drive_thru',
            field=models.BooleanField(default=False),
        ),
    ]
